// @no-cookie-jar
// @name auth-cookie-test

### LOGIN
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=aya&password=mypassword

> {%
    const cookie = response.headers['set-cookie'];
    if (cookie) {
        client.global.set("auth_cookie", cookie);
    }
%}

### CREATE MEETING ROOM
POST http://localhost:8080/api/v1/rooms
Content-Type: application/json
Cookie: JSESSIONID=16B216368756494C7D4AE7C6842CE9C5

{
  "name": "Ocean View Room",
  "description": "Big and bright"
}

### BOOK A ROOM
POST http://localhost:8080/api/v1/reservations?userId=1&roomId=1&start=2025-07-11T09:00:00&end=2025-07-11T10:00:00
Cookie: JSESSIONID=16B216368756494C7D4AE7C6842CE9C5

### CANCEL RESERVATION
DELETE http://localhost:8080/api/v1/reservations/1
Cookie: JSESSIONID=16B216368756494C7D4AE7C6842CE9C5


### Login to get JWT
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "aya",
  "password": "mypassword"
}
###
GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJheWEiLCJpYXQiOjE3NTQxMDIzODksImV4cCI6MTc1NDE4ODc4OX0.3UWkZbiyB56uWfMJaQgi6E8yAg9oOUffY4X7IbFAFpc
